name: No Assertions
on:
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: "Extra Resolve Options"
        required: false
  schedule:
    - cron: "0 1 * * *" # 3 AM CET
  push:
  pull_request:
jobs:
  ndebug:
    name: No Assertions
    uses: steinwurf/nodebug-action/.github/workflows/action.yml@8.0.0
    with:
      extra_resolve_options: ${{ github.events.inputs.extra_resolve_options }}


# Cancel previous in-progress when pushing: https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

# Cancel previous in-progress when pushing: https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true



# Cancel previous in-progress when pushing: https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

