name: Raspberry Pi
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  push:
    branches:
    - master
  pull_request:
jobs:
  RaspberryPi:
    uses: steinwurf/cross-compile-action/.github/workflows/action.yml@6.0.0
    with:
      cxx_mkspec: cxx_raspberry_gxx83_armv7
      extra_resolve_options: ${{ github.event.inputs.extra_resolve_options }}
      image: ghcr.io/steinwurf/gcc-8.3.0-raspberrypi-armv7:1.0.0
      name: Raspberry Pi
      test_binary_directory: build/cxx_raspberry_gxx83_armv7/test
      test_binary_name: cpuid_tests
      test_option: --no_fail
      test_runner: raspberry_pi
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
