name: Windows C++ make-specs
'on':
  workflow_dispatch:
    inputs:
      extra_resolve_options:
        description: Extra Resolve Options
        required: false
  schedule:
  - cron: 0 1 * * *
  push:
    branches:
    - master
  pull_request:
jobs:
  Windows-mkspecs:
    uses: steinwurf/windows-mkspecs-action/.github/workflows/action.yml@6.0.0
    with:
      extra_resolve_options: ${{ github.events.inputs.extra_resolve_options }}
      test_command: python waf --run_tests --run_cmd="%s --no_fail"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
